config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   
  root 'events#index'

  resources :users
  resources :events

  resources :invitations do
    collection do
      get :edit_all
      put :update_all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :invitations, dependent: :destroy
  has_many :attendees, through: :invitations, source: :attendee

  validates :title, :description, :location, :start_date, :end_date, :start_time, :end_time, presence: true
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :event
  
  enum status: {
    no_response: 1,
    accepted: 2,
    rejected: 3
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :created_events, 
    foreign_key: :creator_id,
    class_name: 'Event',
    dependent: :destroy,
    inverse_of: "creator"
  has_many :invitations, 
    foreign_key: :attendee_id, 
    dependent: :destroy, 
    inverse_of: "attendee"
  has_many :attended_events, through: :invitations, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show]
  def index
    @events = Event.all.order("created_at DESC") 
  end

  def show
    @event = Event.find_by(id: params[:id])
    @invitations = @event.invitations.includes([:attendee]).sort_by(&:status)
  end

  def new
    @event = Event.new
    @event.invitations.build #<Invitation id: , status: , created_at:, updated_at: , event_id: attendee_id : >
    @attendee_options = possible_attendees
  end

  def create
    @event = Event.new(event_params)
    @event.creator_id = current_user.id
    @invitation = Invitation.new
    if @event.save
      InvitationManager.new(@event, invitation_params).create_invitations
      redirect_to @event 
    else
      @attendees = invitation_params[:invitations][:attendee_id]
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
    @attendee_options = possible_attendees
    @attendees = @event.attendee_ids
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      InvitationManager.new(@event, invitation_params).update_invitations
      redirect_to @event 
    else
      @attendee_options = possible_attendees
      @attendees = invitation_params[:invitations][:attendee_id]
      render :edit
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path
  end

  private

  def event_params
    params.require(:event).permit(:creator_id,
                                  :title, 
                                  :description, 
                                  :location, 
                                  :start_date, 
                                  :end_date, 
                                  :start_time, 
                                  :end_time)

  end

  def invitation_params
    params.require(:event).permit(invitations: [attendee_id:[]])
  end

  def possible_attendees
    User.all.reject { |user| user == current_user }
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :authenticate_user!, only: [:edit_all, :update_all]

  def edit_all
    @invitations = possible_invitations
    @status_options = possible_statuses
  end

  def update_all
    @invitations = Invitation.update(params[:invitations].keys, params[:invitations].values)
    @invitations.reject! { |invite| invite.errors.empty? }
    if @invitations.empty?
      redirect_to edit_all_invitations_path
    else
      render "edit_all"
    end
  end

  private

  def possible_statuses
    Invitation.statuses.map { |k, _v| [k.capitalize, k] }
  end

  def invitation_params
    params.require(:invitation).permit(:status)
  end

  def possible_invitations
    Invitation.all.includes([event: [:creator]]).select do |invite|
      invite.attendee_id == current_user.id && invite.event.start_date >= Time.now
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
    def sign_up_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div>
  <div>
    <h3>
      <%= event.title %>
    </h3>
    <div class = "block">
      <p>
      <span>
        <i></i>
      </span>
      <%= event.start_date.strftime("%b %-d, %Y") %>
      </p>
    </div>
    <div class="buttons">
      <%= link_to 'Event Details', event_path(id: event.id) %>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with model: @event, local: true do |f| %>
  <% if @event.errors.any? %>
    <div>
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:
      </h2>
      <ul>
        <% @event.errors.each do |error| %>
          <li>
            <span>
              <i></i>
            </span>
            <%= error.full_message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, require: true %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description, required: true %>
  </div>

   <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location, require: true %>
  </div>

  <div class="field">
    <%= f.label "Start Date" %><br />
    <%= f.date_field :start_date, required: true, placeholder: "dd/mm/yyyy", class: "input" %>
  </div>

  <div class="field">
    <%= f.label "Start Time" %><br />
    <%= f.time_field :start_time, require: true, placeholder: "22:00", class: "input" %>
  </div>

  <div class="field">
    <%= f.label "End Date" %><br />
    <%= f.date_field :end_date, require: true, placeholder: "dd/mm/yyyy", class: "input" %>
  </div>

   <div class="field">
    <%= f.label "End Time" %><br />
    <%= f.time_field :end_time, require: true, placeholder: "24:00", class: "input" %>
  </div>
  <div class="field invite-names">
    <p><strong>Invitation Options:</strong></p>
    <%= f.fields_for :invitations do |invite_form| %>
      <%= invite_form.collection_check_boxes :attendee_id, @attendee_options, :id, :name, { checked: @attendees } do |option| %>
        <p>
          <%= option.check_box %>
          <%= option.label %>
        </p>
      <% end %>
    <% end %>
  </div>

  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <h2 class="title is-2">Edit Event</h2>
        <%= render partial: 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/events/index.html.erb
<% if user_signed_in? %>
  <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "button is-helper" %>
  <%= link_to 'Edit your Info', edit_user_registration_path, class: "button is-helper" %>
  <%= link_to 'Invitations', edit_all_invitations_path, class: 'button is-helper' %>
<% else%>
  <%= link_to 'Sign Up', new_user_registration_path, class: "button is-helper" %>
  <%= link_to 'Sign In', new_user_session_path, class:  "button is-helper" %>
<% end %>
<h1><center> All Events</center> </h1>
<% if user_signed_in? %>
<p class="button is-info"><%= link_to 'New Event', new_event_path %></p>
<% end %>
 <% @events.each do |event| %>
   <div class="border">
     <p>
     <%= event.title %>
     on
     <%= event.start_date.strftime("%b %-d, %Y")%>
     <%= event.start_time.strftime(" at %l:%M %P")%>
     <%= link_to 'Event Info', event_path(event.id), class: "button is-show" %>
     </p>
   </div>
 <% end %>

app/views/events/new.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <h2 class="title is-2">New Event</h2>
        <%= render partial: 'form' %>
      </div>
    </div>
  </div>
</section>

app/views/events/show.html.erb
<section class="section">
  <div class="row">
    <div class="column">
      <h2 class="title is-2"><center><%= @event.title %><center></h2>
        <div class="border">
          <h4 class="subtitle is-4">
            Host:
            <%= @event.creator.name %>
          </h4>
          <% unless @event.description.blank? %>
            <p class="pb-3">
            <span class="icon">
              <i class="fa fa-info-circle" aria-hidden="true"></i>
            </span>
            Purpose:
            <%= @event.description %>
            </p>
          <% end %>
            <p class="pb-3">
            <span class="icon">
              <i class="fa fa-info-circle" aria-hidden="true"></i>
            </span>
            Location:
            <%= @event.location %>
            </p>
             <p class="pb-3">
            <span class="icon">
              <i class="fa fa-calendar" aria-hidden="true"></i>
            </span>
            Time:
            <%= @event.start_date.strftime("%b %-d, %Y")%>
            <%= @event.start_time.strftime(" at %l:%M %P")%> -
            <% if (@event.start_date - @event.end_date).to_i == 0 %>
              <%= @event.end_time.strftime("%l:%M %P") %>
            <% else %>
              <%= @event.end_date.strftime("%b %-d, %Y")%>
              <%= @event.end_time.strftime(" at %l:%M %P")%>
            <% end %>
            <% if current_user.id == @event.creator_id %>
              <p><%= link_to "Edit Event", edit_event_path(@event), class: "button is-info" %></p>
              <p><%= link_to "Delete Event", event_path(@event), method: :delete, data: {confirm: "Are you sure you want to delte this event?"}, class: "button is-dangerous" %></p>
            <% end %>
        </div>
             </p>
             <%= link_to 'All Events', root_path, class: "button is-show"%> 
      </div>
    </div>
  </div>
  </div>
  <div class="column">
    <h2 class="title is-2"><center>Guest List</center></h2>
        <div class="border">
          <p> 
          <% @invitations.each do |invite| %>
              <li>
                <%= invite.attendee.name %>
                <% if invite.status == "no_response" %>
                  Status: No Response
                <% elsif invite.status == "accepted" %>
                  Status: Accepted
                <% else %>
                  Status: Declined
                <% end %>
              </li>
            <% end %>
          </p>
        </div>
      </div>
  </div>

</section>

app/views/invitations/edit_all.html.erb
<h2>My Invitations</h2>
<% if @invitations.empty? %>
  <p>No Upcoming Events<p>
<% else %>
  <%= form_tag update_all_invitations_path, method: :put do %>
    <% @invitations.each do |invitation| %>
      <div>
        <div class="border">
          <div>
            <h3>
              <%= link_to invitation.event.title, event_path(id: invitation.event.id) %>
            </h3>
            <h3>
              Host:
              <%= invitation.event.creator.name %>
            </h3>
            <div>
              <% if !invitation.event.description.blank? %>
                <p>
                <i></i>
                <%= invitation.event.description %>
                </p>
              <% end %>
              <p>
              <i></i>
              <%= invitation.event.location %>
              </p>
              <p>
              <i></i>
              <%= invitation.event.start_date.strftime("%b %-d, %Y")%>
              <%= invitation.event.start_time.strftime(" at %l:%M %P")%> -
              <% if (invitation.event.start_date - invitation.event.end_date).to_i == 0 %>
                <%= invitation.event.end_time.strftime("%l:%M %P") %>
              <% else %>
                <%= invitation.event.end_date.strftime("%b %-d, %Y")%>
                <%= invitation.event.end_time.strftime(" at %l:%M %P")%>
              <% end %>
              </p>
            </div>
            <%= fields_for "invitations[]", invitation do |f| %>
              <% if invitation.errors.any? %>
                <div>
                  <h2><%= pluralize(invitation.errors.count, "error") %> prohibited this invitation from being saved:
                  </h2>
                  <ul>
                    <% invitation.errors.full_messages.each do |msg| %>
                      <li><%= msg %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <div>
                <div>
                  <p>
                  <strong>Current RSVP Status</strong> (use dropdown to change & click on save)
                  </p>
                  <div>
                    <%= f.select :status, @status_options %>
                  </div>
                </div>
              </div>
            <% end %>
            <br />
            <div>
              <%= submit_tag "Save Change", class:"button is-show" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <br />
    <div>
      <%= submit_tag "Save All Changes", class:"button is-info " %>
    </div>
    <div>
      <%= link_to "All Events", root_path, class: "button is-dangerous" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h2><%= "#{current_user.name}'s info" %><h2>